import { describe, expect, it } from 'vitest'
import fs from 'node:fs'
import path from 'node:path'

function readSource(relativePath) {
  return fs.readFileSync(path.resolve(process.cwd(), relativePath), 'utf8')
}

describe('App source', () => {
  it('renders the current desktop shell and primary pages', () => {
    const source = readSource('renderer/src/App.vue')
    const sidebarSource = readSource('renderer/src/components/WorkspaceSidebar.vue')

    expect(source).toContain('AppTopBar')
    expect(source).toContain('ActivationGate')
    expect(source).toContain('CommerceOrderModal')
    expect(source).toContain('PermissionActivationModal')
    expect(source).toContain('UserAgreementModal')
    expect(source).toContain('WorkspaceSidebar')
    expect(source).toContain('GenerationCenterPage')
    expect(source).toContain('DataCenterPage')
    expect(source).toContain('ProjectTemplateCenterPage')
    expect(source).toContain('TextGeneratorPage')
    expect(source).toContain('GeneratorStudioPage')
    expect(source).toContain('PurchaseCenterPage')
    expect(source).toContain('AccountDevicePage')
    expect(source).toContain('SettingsCenterPage')
    expect(source).toContain("const activeMenu = ref('work-center')")
    expect(source).toContain("v-else-if=\"activeMenu === 'data-center'\"")
    expect(source).toContain("v-else-if=\"activeMenu === 'template-center'\"")
    expect(source).toContain("v-else-if=\"activeMenu === 'purchase-center'\"")
    expect(source).toContain("v-else-if=\"activeMenu === 'account-device'\"")
    expect(source).not.toContain('WorkbenchOverviewPage')
    expect(source).not.toContain('ResultsCenterPage')

    expect(sidebarSource).toContain('groupedMenuItems')
    expect(sidebarSource).toContain('sidebar-group')
    expect(sidebarSource).toContain('sidebar-menu-button')
  })

  it('keeps workspace, purchase, agreement, and runtime polling flows wired', () => {
    const source = readSource('renderer/src/App.vue')
    const generationCenterSource = readSource('renderer/src/components/GenerationCenterPage.vue')
    const workbenchSource = readSource('renderer/src/components/ProductWorkbench.vue')
    const platformClientSource = readSource('renderer/src/services/platformClient.js')
    const bridgeSource = readSource('renderer/src/services/desktopBridge.js')
    const studioIpcSource = readSource('main/src/ipc/studioIpc.js')
    const channelSource = readSource('shared/ipcChannels.js')

    expect(source).toContain('@create-project="handleCreateProject"')
    expect(source).toContain('@run-project="handleRunProject"')
    expect(source).toContain('@open-generator="handleOpenProjectGenerator"')
    expect(source).toContain('@export-project="handleExportProject"')
    expect(source).toContain('@activate-permission="openPermissionActivation"')
    expect(source).toContain('@clear-permission="handleClearPermission"')
    expect(source).toContain('@submit-software-order="handleCreateSoftwareOrder"')
    expect(source).toContain('@accept="handleAcceptUserAgreement"')
    expect(source).toContain('createRechargeOrderController({')
    expect(source).toContain('createSoftwareOrderController({')
    expect(source).toContain('createComputePackageOrderController({')
    expect(source).toContain('const runtimePollingIntervalMs = 1500')
    expect(source).toContain('const publishTaskPollingProfile = {')
    expect(source).toContain('const snapshot = await workspaceClient.getRuntimeSnapshot()')
    expect(source).toContain('const task = await publishClient.getTask({')
    expect(source).toContain('queuePublishTaskPolling(0)')

    expect(generationCenterSource).toContain('work-center-studio')
    expect(generationCenterSource).toContain('generator-column--settings')
    expect(generationCenterSource).toContain('generator-column--preview')
    expect(generationCenterSource).toContain('generator-column--export')
    expect(workbenchSource).toContain("emit('create-project')")
    expect(workbenchSource).toContain("emit('run-project'")
    expect(workbenchSource).toContain("emit('open-generator'")
    expect(platformClientSource).toContain('export const workspaceClient = {')
    expect(platformClientSource).toContain('getRuntimeSnapshot: getStudioRuntimeSnapshot')
    expect(bridgeSource).toContain("export function getStudioRuntimeSnapshot () {")
    expect(channelSource).toContain("STUDIO_GET_RUNTIME_SNAPSHOT: 'studio:get-runtime-snapshot'")
    expect(studioIpcSource).toContain('ipcMain.handle(ipcChannels.STUDIO_GET_RUNTIME_SNAPSHOT')
  })

  it('keeps the new balance guard hooks in the desktop app source', () => {
    const source = readSource('renderer/src/App.vue')
    const lifecycleSource = readSource('main/src/services/workspaceTaskLifecycleService.js')
    const creditSource = readSource('main/src/services/workspaceCreditService.js')

    expect(source).toContain('function getWalletBalanceSummary() {')
    expect(source).toContain('function assertClientSideBalanceForTask({ menuKey, draft, textKind = \'\' } = {}) {')
    expect(source).toContain("title: '余额不足'")
    expect(lifecycleSource).toContain('function resolveTaskBalanceRequirements(menuKey, draft = {}) {')
    expect(lifecycleSource).toContain('function assertSufficientWalletBalance({ menuKey, draft, dashboardCreditState }) {')
    expect(lifecycleSource).toContain('const creditSyncResult = await syncCreditStateWithRealtimeBalance()')
    expect(creditSource).toContain('async function syncCreditStateWithRealtimeBalance() {')
    expect(creditSource).toContain("target: 'all'")
  })
})
