import { describe, expect, it } from 'vitest'
import fs from 'node:fs'
import path from 'node:path'

function readSource(relativePath) {
  return fs.readFileSync(path.resolve(process.cwd(), relativePath), 'utf8')
}

describe('App source', () => {
  it('renders the simplified desktop shell and new primary navigation map', () => {
    const source = readSource('renderer/src/App.vue')
    const sidebarSource = readSource('renderer/src/components/WorkspaceSidebar.vue')

    expect(source).toContain('AppTopBar')
    expect(source).toContain('ActivationGate')
    expect(source).toContain('AuthorizationPurchaseModal')
    expect(source).toContain('WorkspaceSidebar')
    expect(source).toContain('WorkbenchOverviewPage')
    expect(source).toContain('GenerationCenterPage')
    expect(source).toContain('TextGeneratorPage')
    expect(source).toContain('GeneratorStudioPage')
    expect(source).toContain('ResultsCenterPage')
    expect(source).toContain('PurchaseCenterPage')
    expect(source).toContain('AccountDevicePage')
    expect(source).toContain('SettingsCenterPage')
    expect(source).toContain("import studioMenuConfig from '../../shared/studio-menu-config.json'")
    expect(source).toContain('const menuItems = Array.isArray(studioMenuConfig.primaryMenuItems)')
    expect(source).toContain("const activeMenu = ref('workbench')")
    expect(source).toContain('const authorizationPurchaseModalVisible = ref(false)')
    expect(source).toContain('<main class="app-shell" data-theme="dark">')
    expect(source).not.toContain('DataCenterPage')
    expect(source).not.toContain('PromptLibraryPanel')
    expect(source).not.toContain("key: 'title-generator'")
    expect(source).not.toContain("key: 'description-generator'")
    expect(source).not.toContain("key: 'account-usage'")
    expect(source).toContain("key: 'prompt-library'")

    expect(sidebarSource).toContain('groupedMenuItems')
    expect(sidebarSource).toContain('sidebar-group')
    expect(sidebarSource).toContain('sidebar-menu-button')
    expect(sidebarSource).toContain('QiuAi ECMS')
    expect(sidebarSource).toContain("const groupOrder = ['")
  })

  it('keeps the workspace and generator flows wired through grouped service clients', () => {
    const source = readSource('renderer/src/App.vue')
    const generationCenterSource = readSource('renderer/src/components/GenerationCenterPage.vue')
    const workbenchSource = readSource('renderer/src/components/ProductWorkbench.vue')
    const draftBuilderSource = readSource('renderer/src/utils/generatorDraftBuilders.js')
    const validationSource = readSource('renderer/src/utils/generatorTaskValidation.js')
    const outputLocatorSource = readSource('renderer/src/utils/workspaceOutputLocators.js')
    const platformClientSource = readSource('renderer/src/services/platformClient.js')

    expect(source).toContain('@create-project="handleCreateProject"')
    expect(source).toContain('@run-project="handleRunProject"')
    expect(source).toContain('@open-generator="handleOpenProjectGenerator"')
    expect(generationCenterSource).toContain('ProductWorkbench')
    expect(generationCenterSource).toContain('generatorShortcutOptions')
    expect(generationCenterSource).toContain("emit('open-generator', { project: null, menuKey })")
    expect(generationCenterSource).toContain("emit('run-project', item.project)")
    expect(generationCenterSource).toContain('isAdvancedWorkspaceVisible')

    expect(source).toContain('workspaceClient.createProject')
    expect(source).toContain('workspaceClient.updateProject')
    expect(source).toContain('workspaceClient.deleteProject')
    expect(source).toContain('workspaceClient.exportProjectBundle')
    expect(source).toContain('workspaceClient.pickInputAssets')
    expect(source).toContain('shellClient.openOutputDirectory')
    expect(source).toContain('selectionClient.getManifest')
    expect(source).toContain('selectionClient.listItems')
    expect(source).toContain('publishClient.getConfig')
    expect(source).toContain('publishClient.createTask')
    expect(source).toContain('publishClient.retryTask')
    expect(source).toContain('promptLibraryClient.listTemplates')
    expect(source).toContain('handleCreateProject')
    expect(source).toContain('handleProjectUpdate')
    expect(source).toContain('handleProjectDelete')
    expect(source).toContain('handleOpenImages')
    expect(source).toContain('handleOpenVideo')
    expect(source).toContain('handleExportProject')
    expect(source).toContain('buildProjectTextGeneratorDraft')
    expect(source).toContain("import { validateGeneratorTaskDraft } from './utils/generatorTaskValidation'")
    expect(source).toContain("import { validatePublishDraftBeforeRemote } from './utils/publishDraftValidation'")
    expect(source).toContain('function normalizeProjectRunPayload(payload = null) {')
    expect(source).toContain('const latestRun = resolveLatestRun(project, projectRuns.value, run)')
    expect(source).toContain('const imageDirectory = resolveImageOutputDirectory(project, latestRun)')
    expect(source).toContain('const videoDirectory = resolveVideoOutputDirectory(project, latestRun)')
    expect(source).toContain('@update-project="handleProjectUpdate"')
    expect(source).toContain('@delete-project="handleProjectDelete"')
    expect(source).toContain('@selection-query-change="handleSelectionQueryChange"')
    expect(source).toContain('@selection-import="handleSelectionImport"')
    expect(source).toContain('@publish-sync-task="handlePublishSyncTask"')
    expect(source).toContain('@publish-retry-task="handlePublishRetryTask"')
    expect(source).toContain('async function ensurePublishDraftReady(project) {')
    expect(source).toContain('function resolveProjectPublishTaskOperation(project = {}) {')
    expect(source).toContain('const localValidationError = validateProjectPublishDraftBeforeRemote(project, selectedPlatform, profile, operationType)')

    expect(workbenchSource).toContain("emit('create-project')")
    expect(workbenchSource).toContain("emit('update-project'")
    expect(workbenchSource).toContain("emit('delete-project'")
    expect(workbenchSource).toContain("emit('selection-query-change'")
    expect(workbenchSource).toContain("emit('selection-import'")
    expect(workbenchSource).toContain("emit('open-generator'")
    expect(workbenchSource).toContain('normalizeProjectPublishDraft,')

    expect(draftBuilderSource).toContain('export function buildProjectGeneratorDraft(project, menuKey) {')
    expect(draftBuilderSource).toContain('export function buildWorkspaceRunDraft(project, workspaceDraft = {}) {')
    expect(draftBuilderSource).toContain("export function buildProjectTextGeneratorDraft(project, workspaceDraft = {}, kind = 'title') {")
    expect(validationSource).toContain("menuKey === 'series-generate'")
    expect(validationSource).toContain("menuKey === 'video-generate'")
    expect(outputLocatorSource).toContain('export function resolveLatestRun(project, projectRuns = [], run = null) {')
    expect(outputLocatorSource).toContain('export function resolveImageOutputDirectory(project, latestRun) {')
    expect(outputLocatorSource).toContain('export function resolveVideoOutputDirectory(project, latestRun) {')

    expect(platformClientSource).toContain('export const activationClient = {')
    expect(platformClientSource).toContain('export const selectionClient = {')
    expect(platformClientSource).toContain('export const publishClient = {')
    expect(platformClientSource).toContain('export const workspaceClient = {')
    expect(platformClientSource).toContain('getRuntimeSnapshot: getStudioRuntimeSnapshot')
  })

  it('keeps four generator entry views and runtime tasks aligned with the simplified shell', () => {
    const source = readSource('renderer/src/App.vue')
    const generatorSource = readSource('renderer/src/components/GeneratorStudioPage.vue')
    const textGeneratorSource = readSource('renderer/src/components/TextGeneratorPage.vue')
    const generatorViewSource = readSource('renderer/src/utils/generatorViews.js')

    expect(source).toContain("from './utils/generatorViews'")
    expect(generatorViewSource).toContain("import studioMenuConfig from '../../../shared/studio-menu-config.json'")
    expect(generatorViewSource).toContain('export const generatorViewMap = studioMenuConfig.generatorViews || {}')
    expect(generatorViewSource).toContain('export function resolveGeneratorView(menuKey) {')
    expect(source).toContain("if (activeMenu.value !== 'generation-center') {")
    expect(source).toContain("return (activeMenu.value === 'workbench' || activeMenu.value === 'generation-center') && !isWorkspaceGeneratorView.value")
    expect(source).toContain("if (menuKey === 'generation-center' && formDrafts.value.workspace?.projectId)")
    expect(source).toContain("activeMenu.value = 'generation-center'")
    expect(source).toContain('activeGeneratorMenu.value = menuKey')
    expect(source).toContain('const isWorkspaceHome = computed(() => {')
    expect(source).toContain('v-if="isWorkspaceHome"')
    expect(source).toContain('v-else-if="activeTextGeneratorView"')
    expect(source).toContain('v-else-if="activeMediaGeneratorView"')
    expect(source).toContain(':title="activeTextGeneratorView.title"')
    expect(source).toContain(':text-kind="activeTextGeneratorView.textKind"')
    expect(source).toContain(':title="activeMediaGeneratorView.title"')
    expect(source).toContain(':mode="activeMediaGeneratorView.mode"')
    expect(source).toContain('@submit-task="handleSubmitTask(activeGeneratorMenuKey)"')
    expect(source).toContain('@submit-task="handleSubmitTextGenerator(activeTextGeneratorView.textKind)"')
    expect((source.match(/<GeneratorStudioPage/g) || []).length).toBe(1)
    expect((source.match(/<TextGeneratorPage/g) || []).length).toBe(1)
    expect(generatorViewSource).toContain('generatorShortcutOptions')

    expect(generatorSource).toContain('generator-column__header')
    expect(generatorSource).toContain('generator-form')
    expect(generatorSource).toContain('generator-preview')
    expect(generatorSource).toContain('generator-export')
    expect(generatorSource).toContain("mode === 'video'")
    expect(textGeneratorSource).toContain("const isTitleMode = computed(() => props.textKind === 'title')")
    expect(textGeneratorSource).toContain("emit('submit-task')")
    expect(textGeneratorSource).toContain("emit('copy-text', item.content || '')")
    expect(textGeneratorSource).toContain("emit('export-results')")
  })

  it('promotes purchase, account, results, and settings into the primary shell', () => {
    const source = readSource('renderer/src/App.vue')
    const overviewSource = readSource('renderer/src/components/WorkbenchOverviewPage.vue')
    const resultsSource = readSource('renderer/src/components/ResultsCenterPage.vue')
    const accountSource = readSource('renderer/src/components/AccountDevicePage.vue')
    const settingsSource = readSource('renderer/src/components/SettingsCenterPage.vue')
    const purchaseControllerConfigSource = readSource('renderer/src/utils/purchaseControllerConfigs.js')

    expect(source).toContain('v-if="isWorkspaceHome"')
    expect(source).toContain(':current-recharge-order="currentRechargeOrder"')
    expect(source).toContain(':current-software-order="currentSoftwareOrder"')
    expect(source).toContain(':current-compute-package-order="currentComputePackageOrder"')
    expect(source).toContain('<AuthorizationPurchaseModal')
    expect(source).toContain('@submit-order="handleCreateSoftwareOrder"')
    expect(source).not.toContain('embeddedPurchaseCenterRef')
    expect(source).toContain("v-else-if=\"activeMenu === 'results-center'\"")
    expect(source).toContain("v-else-if=\"activeMenu === 'purchase-center'\"")
    expect(source).toContain("v-else-if=\"activeMenu === 'account-device'\"")
    expect(source).toContain("v-else-if=\"activeMenu === 'prompt-library' || activeMenu === 'settings-center'\"")
    expect(source).toContain('@refresh-catalog="loadPurchaseCenterCatalog"')
    expect(source).toContain('@update-recharge-form="handleRechargeFormUpdate"')
    expect(source).toContain('@create-recharge="handleCreateRecharge"')
    expect(source).toContain('rechargeOrderController = createRechargeOrderController({')
    expect(source).toContain('softwareOrderController = createSoftwareOrderController({')
    expect(source).toContain('computePackageOrderController = createComputePackageOrderController({')

    expect(overviewSource).toContain('DataCenterPage')
    expect(overviewSource).toContain('const walletCards = computed(() => {')
    expect(overviewSource).toContain('const recentOrders = computed(() => {')
    expect(overviewSource).toContain('const recentOutputs = computed(() => {')
    expect(overviewSource).toContain('最小闭环')
    expect(overviewSource).toContain('最近订单')
    expect(overviewSource).toContain('最近结果')
    expect(overviewSource).not.toContain('这里作为客户端启动后的总入口')
    expect(resultsSource).toContain("defineEmits(['open-output'])")
    expect(resultsSource).not.toContain('集中查看最近任务状态')
    expect(accountSource).toContain("defineEmits(['copy-device-code'])")
    expect(accountSource).not.toContain('查看当前账号')
    expect(settingsSource).toContain('PromptLibraryPanel')
    expect(settingsSource).not.toContain('这一轮先把提示词配置收口')
    expect(purchaseControllerConfigSource).toContain('export function createRechargeOrderController({')
    expect(purchaseControllerConfigSource).toContain('export function createSoftwareOrderController({')
    expect(purchaseControllerConfigSource).toContain('export function createComputePackageOrderController({')
  })

  it('keeps polling scoped to local runtime snapshot and publish task refresh', () => {
    const appSource = readSource('renderer/src/App.vue')
    const bridgeSource = readSource('renderer/src/services/desktopBridge.js')
    const studioIpcSource = readSource('main/src/ipc/studioIpc.js')
    const channelSource = readSource('shared/ipcChannels.js')

    expect(appSource).toContain('const runtimePollingIntervalMs = 1500')
    expect(appSource).toContain('const publishTaskPollingProfile = {')
    expect(appSource).toContain('function resolvePublishTaskBlockingIssues(task = null) {')
    expect(appSource).toContain('const snapshot = await workspaceClient.getRuntimeSnapshot()')
    expect(appSource).toContain('const task = await publishClient.getTask({')
    expect(appSource).toContain('queuePublishTaskPolling(resolvePublishPollingDelayMs(')
    expect(appSource).toContain('queuePublishTaskPolling(0)')
    expect(appSource).not.toContain('getGenerationJob(')
    expect(appSource).not.toContain('/api/generation/jobs')
    expect(appSource).not.toContain('/api/activation/status')

    expect(bridgeSource).toContain("export function getStudioRuntimeSnapshot () {")
    expect(bridgeSource).toContain("return invoke(getChannel('STUDIO_GET_RUNTIME_SNAPSHOT'))")
    expect(channelSource).toContain("STUDIO_GET_RUNTIME_SNAPSHOT: 'studio:get-runtime-snapshot'")
    expect(studioIpcSource).toContain('ipcMain.handle(ipcChannels.STUDIO_GET_RUNTIME_SNAPSHOT')
    expect(studioIpcSource).toContain('return studioWorkspaceService.getRuntimeSnapshot()')
  })
})
