import { describe, expect, it } from 'vitest'
import fs from 'node:fs'
import path from 'node:path'

describe('App source', () => {
  it('renders the simplified product workspace shell and current navigation map', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')
    const sidebarSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/WorkspaceSidebar.vue'), 'utf8')

    expect(source).toContain('AppTopBar')
    expect(source).toContain('ActivationGate')
    expect(source).toContain('WorkspaceSidebar')
    expect(source).toContain('ProductWorkbench')
    expect(source).toContain('DataCenterPage')
    expect(source).toContain('ProductTemplateDemoPage')
    expect(source).toContain('GeneratorStudioPage')
    expect(source).toContain('PromptLibraryPanel')
    expect(source).toContain('ModelConfigPage')
    expect(source).toContain('const menuItems = [')
    expect(source).toContain("key: 'workspace'")
    expect(source).toContain("key: 'data-center'")
    expect(source).toContain("key: 'product-template'")
    expect(source).toContain("key: 'title-generator'")
    expect(source).toContain("key: 'description-generator'")
    expect(source).toContain("key: 'series-generate'")
    expect(source).toContain("key: 'video-generate'")
    expect(source).toContain("key: 'model-pricing'")
    expect(source).toContain("key: 'prompt-library'")
    expect(source).toContain("key: 'model-config'")
    expect(source).not.toContain('AdminPasswordDialog')
    expect(source).not.toContain('AdminApiKeyDialog')
    expect(source).not.toContain('saveAdminApiKey')
    expect(source).toContain('saveProviderApiKeys')

    expect(sidebarSource).toContain('groupedMenuItems')
    expect(sidebarSource).toContain('sidebar-group')
    expect(sidebarSource).toContain('sidebar-menu-button')
    expect(sidebarSource).toContain('QiuAi ECMS')
  })

  it('wires the product workbench actions and card result actions through the desktop bridge handlers', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')
    const workbenchSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/ProductWorkbench.vue'), 'utf8')

    expect(source).toContain('createStudioProject')
    expect(source).toContain('createProjectsFromAssets')
    expect(source).toContain('updateStudioProject')
    expect(source).toContain('deleteStudioProject')
    expect(source).toContain('exportStudioProjectBundle')
    expect(source).toContain('pickStudioInputAssets')
    expect(source).toContain('openOutputDirectory')
    expect(source).toContain('handleCreateProject')
    expect(source).toContain('handleProjectUpdate')
    expect(source).toContain('handleProjectDelete')
    expect(source).toContain('handleOpenImages')
    expect(source).toContain('handleOpenVideo')
    expect(source).toContain('handleExportProject')
    expect(source).toContain('handleCopyText')
    expect(source).toContain('@create-project="handleCreateProject"')
    expect(source).toContain('@update-project="handleProjectUpdate"')
    expect(source).toContain('@delete-project="handleProjectDelete"')
    expect(source).toContain('@copy-text="handleCopyText"')
    expect(source).toContain('@open-images="handleOpenImages"')
    expect(source).toContain('@open-video="handleOpenVideo"')
    expect(source).toContain('@export-project="handleExportProject"')
    expect(source).toContain('activeProductProjectId')

    expect(workbenchSource).toContain("emit('create-project')")
    expect(workbenchSource).toContain("emit('update-project'")
    expect(workbenchSource).toContain("emit('delete-project'")
    expect(workbenchSource).toContain("emit('copy-text'")
    expect(workbenchSource).toContain("emit('open-images'")
    expect(workbenchSource).toContain("emit('open-video'")
    expect(workbenchSource).toContain("emit('export-project'")
    expect(workbenchSource).toContain('project-draft-card')
    expect(workbenchSource).toContain('product-result-card')
    expect(workbenchSource).toContain('product-result-card__detail-row')
    expect(workbenchSource).not.toContain('effect-display')
    expect(source).not.toContain('@batch-upload="handleBatchUpload"')
    expect(source).not.toContain('@run-batch-projects="handleRunBatchProjects"')
    expect(source).not.toContain('@update-draft="handleWorkbenchDraftUpdate"')
  })

  it('keeps all four generator pages on one shared studio component shape', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')
    const generatorSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/GeneratorStudioPage.vue'), 'utf8')

    expect(source).toContain("v-else-if=\"activeMenu === 'title-generator'\"")
    expect(source).toContain('title="标题生成"')
    expect(source).toContain("mode=\"title\"")
    expect(source).toContain("v-else-if=\"activeMenu === 'description-generator'\"")
    expect(source).toContain('title="描述生成"')
    expect(source).toContain("mode=\"description\"")
    expect(source).toContain("v-else-if=\"activeMenu === 'series-generate'\"")
    expect(source).toContain('title="套图生成"')
    expect(source).toContain("mode=\"image\"")
    expect(source).toContain("v-else-if=\"activeMenu === 'video-generate'\"")
    expect(source).toContain('title="视频生成"')
    expect(source).toContain("mode=\"video\"")
    expect(source).toContain('@pick-image="handlePickGeneratorImage"')
    expect(source).toContain(':prompt-templates="promptTemplates"')
    expect(source).toContain('@open-export-item="handleOpenGeneratorExportItem"')

    expect(generatorSource).toContain('generator-column__header')
    expect(generatorSource).toContain('generator-form')
    expect(generatorSource).toContain('generator-preview')
    expect(generatorSource).toContain('generator-export')
    expect(generatorSource).toContain("mode === 'title'")
    expect(generatorSource).toContain("mode === 'description'")
    expect(generatorSource).toContain("mode === 'video'")
    expect(generatorSource).toContain("emit('submit-task')")
    expect(generatorSource).toContain("emit('pick-image')")
    expect(generatorSource).toContain("emit('open-export-item', item)")
    expect(generatorSource).toContain('titleMaxChars')
    expect(generatorSource).toContain('descriptionMaxChars')
    expect(generatorSource).toContain('motionStrength')
    expect(generatorSource).toContain('generator-form__series')
    expect(generatorSource).toContain('differenceLevelOptions')
    expect(generatorSource).toContain('参数设置')
    expect(generatorSource).toContain('任务进度')
    expect(generatorSource).toContain('结果导出')
  })

  it('defines the current pricing cards and simplified model config inputs for the e-commerce upgrade', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')
    const modelConfigSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/ModelConfigPage.vue'), 'utf8')
    const dataCenterSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/DataCenterPage.vue'), 'utf8')

    expect(source).toContain('const pricingCards = computed(() => {')
    expect(source).toContain('const pricingSections = computed(() => {')
    expect(source).toContain('const pricingSectionStyleMap = {')
    expect(source).toContain("title: 'deepseek-v4-flash'")
    expect(source).toContain("title: 'deepseek-v4-pro'")
    expect(source).toContain("title: 'nano-banana-fast'")
    expect(source).toContain("title: 'gpt-image-2'")
    expect(source).toContain("title: 'nano-banana-2'")
    expect(source).toContain("title: 'MiniMax-Hailuo-2.3-Fast'")
    expect(source).toContain("categoryKey: 'text'")
    expect(source).toContain("categoryKey: 'image'")
    expect(source).toContain("categoryKey: 'video'")
    expect(source).toContain("categoryLabel: '文本'")
    expect(source).toContain("categoryLabel: '图片'")
    expect(source).toContain("categoryLabel: '视频'")
    expect(source).toContain('pricing-section__grid')
    expect(source).toContain('pricing-card__row')
    expect(source).not.toContain("title: 'gemini-3-pro'")
    expect(source).not.toContain("title: 'sora-create-character'")

    expect(source).toContain('handleSaveModelConfig')
    expect(source).toContain(':text-api-key="modelConfigTextApiKeyDraft"')
    expect(source).toContain(':image-api-key="modelConfigImageApiKeyDraft"')
    expect(source).toContain(':video-api-key="modelConfigVideoApiKeyDraft"')
    expect(modelConfigSource).toContain('textApiKey')
    expect(modelConfigSource).toContain('imageApiKey')
    expect(modelConfigSource).toContain('videoApiKey')
    expect(modelConfigSource).toContain("emit('update-text-api-key'")
    expect(modelConfigSource).toContain("emit('update-image-api-key'")
    expect(modelConfigSource).toContain("emit('update-video-api-key'")
    expect(modelConfigSource).toContain("emit('save')")
    expect(modelConfigSource).toContain('model-config-stack')
    expect(modelConfigSource).not.toContain('modelGroups')

    expect(dataCenterSource).toContain('credit-record-panel')
    expect(dataCenterSource).not.toContain('right-sidebar')
  })

  it('does not keep the removed generator-page workspace bridge', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')
    const generatorSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/GeneratorStudioPage.vue'), 'utf8')

    expect(source).not.toContain(':linked-project="currentLinkedProject"')
    expect(source).not.toContain('@open-workspace-project="handleMenuSelect(\'workspace\')"')
    expect(generatorSource).not.toContain('generator-project-context')
    expect(generatorSource).not.toContain('open-workspace-project')
  })
})
