import { describe, expect, it } from 'vitest'
import fs from 'node:fs'
import path from 'node:path'
import { parse } from '@vue/compiler-sfc'

describe('component sources', () => {
  it('parses the new page components without template syntax errors', () => {
    const componentPaths = [
      'renderer/src/components/ProductWorkbench.vue',
      'renderer/src/components/DataCenterPage.vue',
      'renderer/src/components/GeneratorStudioPage.vue',
      'renderer/src/components/PurchaseCenterPage.vue',
      'renderer/src/components/PromptLibraryPanel.vue'
    ]

    componentPaths.forEach((componentPath) => {
      const source = fs.readFileSync(path.resolve(process.cwd(), componentPath), 'utf8')
      expect(() => parse(source)).not.toThrow()
    })
  })

  it('keeps the top bar and activation gate aligned with the current desktop shell', () => {
    const topbarSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/AppTopBar.vue'), 'utf8')
    const activationSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/ActivationGate.vue'), 'utf8')

    expect(topbarSource).not.toContain('brand-click')
    expect(topbarSource).toContain('cleanup-click')
    expect(topbarSource).not.toContain('theme-change')
    expect(topbarSource).toContain('contact-preview-modal')
    expect(topbarSource).toContain('topbar-clean-button')
    expect(topbarSource).toContain('brandLabel')
    expect(topbarSource).not.toContain('themeOptions')
    expect(topbarSource).not.toContain('activeTheme')
    expect(topbarSource).not.toContain('topbar-theme')

    expect(activationSource).toContain('copy-device-code')
    expect(activationSource).toContain('activationState.deviceCode')
    expect(activationSource).not.toContain('import-license')
    expect(activationSource).not.toContain('refresh-license')
  })

  it('uses product-card workbench layout and simplified account-usage page', () => {
    const workbenchSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/ProductWorkbench.vue'), 'utf8')
    const dataCenterSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/DataCenterPage.vue'), 'utf8')
    const generatorViewSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/utils/generatorViews.js'), 'utf8')

    expect(workbenchSource).toContain('workbench-plus-button')
    expect(workbenchSource).toContain("import { generatorShortcutOptions } from '../utils/generatorViews'")
    expect(workbenchSource).toContain('project-draft-grid')
    expect(workbenchSource).toContain('project-draft-card__title')
    expect(workbenchSource).toContain('project-draft-card__meta')
    expect(workbenchSource).toContain('project-draft-card__media')
    expect(workbenchSource).toContain('product-result-grid')
    expect(workbenchSource).toContain('product-result-card__copy')
    expect(workbenchSource).toContain('project-draft-card__delete')
    expect(workbenchSource).toContain('product-result-card__detail')
    expect(workbenchSource).toContain('selection-panel__filters')
    expect(workbenchSource).toContain('selection-card__actions')
    expect(workbenchSource).toContain("@click=\"emit('export-project', item.project.id)\"")
    expect(workbenchSource).toContain('resolveLatestTaskRemoteListingId')
    expect(workbenchSource).toContain('resolveLatestTaskRemoteReviewStatus')
    expect(workbenchSource).toContain('resolveLatestTaskOutcome')
    expect(workbenchSource).toContain('resolveLatestTaskPollingAdvice')
    expect(workbenchSource).toContain('resolveLatestTaskPollingIntervalLabel')
    expect(workbenchSource).toContain('resolveLatestTaskPollingAdviceText')
    expect(workbenchSource).toContain('resolveLatestTaskOperatorGuidance')
    expect(workbenchSource).toContain('resolveLatestTaskOperatorGuidanceSummary')
    expect(workbenchSource).toContain('resolveLatestTaskOperatorGuidanceActions')
    expect(workbenchSource).toContain('const blockingIssues = getPublishState(projectId).latestTask?.blockingIssues')
    expect(workbenchSource).toContain('function resolvePublishIssueFieldLabel(issue = {}) {')
    expect(workbenchSource).toContain("if (field === 'media[0].publishReadyUrl') return 'Primary Media Publish URL'")
    expect(workbenchSource).toContain("if (field === 'platformDraft.categoryId') return 'Category ID'")
    expect(workbenchSource).toContain("if (field.startsWith('platformDraft.attributes.')) {")
    expect(workbenchSource).toContain('function resolvePublishIssueSuggestedFix(issue = {}) {')
    expect(workbenchSource).toContain("Suggestion: ${resolvePublishIssueSuggestedFix(issue)}")
    expect(workbenchSource).toContain('function registerPublishFieldRef(projectId = \'\', fieldKey = \'\') {')
    expect(workbenchSource).toContain('function focusPublishIssueField(project = {}, issue = {}) {')
    expect(workbenchSource).toContain('Locate Field')
    expect(workbenchSource).toContain(":ref=\"registerPublishFieldRef(item.project.id, 'media')\"")
    expect(workbenchSource).toContain(":ref=\"registerPublishFieldRef(item.project.id, 'categoryId')\"")
    expect(workbenchSource).toContain('lastAttempt?.requestSummary?.ruleVersion')
    expect(workbenchSource).toContain('lastAttempt?.responseSummary?.remoteReviewStatus')
    expect(workbenchSource).toContain('resolveSelectedChannelAccountStatusLabel')
    expect(workbenchSource).toContain('resolveSelectedChannelAccountReadiness')
    expect(workbenchSource).toContain('isSelectedChannelAccountUsable')
    expect(workbenchSource).toContain('Account Status:')
    expect(workbenchSource).toContain('Submission Readiness:')
    expect(workbenchSource).toContain('readinessMessage')
    expect(workbenchSource).toContain('function resolveDraftReadiness(projectId = \'\') {')
    expect(workbenchSource).toContain('function resolveDraftReadinessStaleMessage(projectId = \'\') {')
    expect(workbenchSource).toContain('function resolveProjectPublishMediaStatus(project = {}) {')
    expect(workbenchSource).toContain('function resolvePlatformDraftReadiness(project = {}) {')
    expect(workbenchSource).toContain('function resolvePlatformDraftReadinessIssues(project = {}) {')
    expect(workbenchSource).toContain('Draft Readiness: READY')
    expect(workbenchSource).toContain('Draft Readiness: INCOMPLETE')
    expect(workbenchSource).toContain('Draft Readiness: STALE')
    expect(workbenchSource).toContain('Publish Media: READY_REMOTE')
    expect(workbenchSource).toContain('Publish Media: LOCAL_ONLY')
    expect(workbenchSource).toContain('Publish Media: MISSING')
    expect(workbenchSource).toContain('Create Listing: READY')
    expect(workbenchSource).toContain('Create Listing: INCOMPLETE')
    expect(workbenchSource).toContain('Missing Fields:')
    expect(workbenchSource).toContain('Platform Missing Fields:')
    expect(workbenchSource).toContain('Platform Readiness Issues')
    expect(workbenchSource).toContain("'publish-sync-task'")
    expect(workbenchSource).toContain("emit('publish-sync-task', item.project)")
    expect(workbenchSource).toContain('Remote Listing ID:')
    expect(workbenchSource).toContain('Review Status:')
    expect(workbenchSource).toContain('Attempt Outcome:')
    expect(workbenchSource).toContain('Polling Advice:')
    expect(workbenchSource).toContain('Operator Guidance:')
    expect(workbenchSource).toContain('Recovery Checklist')
    expect(workbenchSource).toContain('平台审核中，建议')
    expect(workbenchSource).toContain('任务已入队，客户端将按约')
    expect(workbenchSource).toContain('任务执行中，客户端将按约')
    expect(workbenchSource).toContain("String(account.status || '').toUpperCase()")
    expect(workbenchSource).not.toContain('promptTemplates: { type: Array')
    expect(workbenchSource).not.toContain('effect-display')
    expect(workbenchSource).not.toContain('workbench-agent-shell')
    expect(workbenchSource).not.toContain('workbench-agent-card')
    expect(generatorViewSource).toContain('export const generatorShortcutOptions = Object.entries(generatorViewMap).map')
    expect(generatorViewSource).not.toContain('title-generator')
    expect(generatorViewSource).not.toContain('description-generator')
    expect(generatorViewSource).toContain('shortcutLabel')

    expect(dataCenterSource).toContain('data-center-gauge-row')
    expect(dataCenterSource).toContain('credit-gauge-card')
    expect(dataCenterSource).toContain('credit-record-panel')
    expect(dataCenterSource).toContain("key: 'text'")
    expect(dataCenterSource).toContain("key: 'image'")
    expect(dataCenterSource).toContain("key: 'video'")
  })

  it('uses the unified generator studio and keeps purchase center plus prompt library available', () => {
    const generatorSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/GeneratorStudioPage.vue'), 'utf8')
    const purchaseCenterSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/PurchaseCenterPage.vue'), 'utf8')
    const promptLibrarySource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/PromptLibraryPanel.vue'), 'utf8')

    expect(generatorSource).toContain('generator-column__header')
    expect(generatorSource).toContain('generator-form')
    expect(generatorSource).toContain('generator-preview')
    expect(generatorSource).toContain('generator-export')
    expect(generatorSource).toContain("emit('pick-image')")
    expect(generatorSource).toContain('generator-form__series')
    expect(generatorSource).toContain('seriesPromptAssignments')
    expect(generatorSource).toContain('differenceLevel')
    expect(generatorSource).not.toContain('generator-project-context')
    expect(generatorSource).toContain('videoTemplateId')
    expect(generatorSource).toContain('imageTemplateDefaultOrder')
    expect(generatorSource).toContain('handleSeriesAssignmentTemplateChange')
    expect(generatorSource).not.toContain('titleTemplateId')
    expect(generatorSource).not.toContain('descriptionTemplateId')

    expect(purchaseCenterSource).toContain('purchase-center__hero')
    expect(purchaseCenterSource).toContain('purchase-center__wallet-grid')
    expect(purchaseCenterSource).toContain("emit('refresh-catalog')")
    expect(purchaseCenterSource).toContain("emit('update-recharge-form'")
    expect(purchaseCenterSource).toContain("emit('create-recharge')")
    expect(purchaseCenterSource).toContain('purchase-center__recharge-form')

    expect(promptLibrarySource).toContain('CATEGORY_ORDER')
    expect(promptLibrarySource).toContain('templatesByCategory')
    expect(promptLibrarySource).toContain('expandedTemplateId')
    expect(promptLibrarySource).toContain('save-template')
    expect(promptLibrarySource).toContain('remove-template')
    expect(promptLibrarySource).toContain('提示词库')
    expect(promptLibrarySource).toContain('标题')
    expect(promptLibrarySource).toContain('描述')
    expect(promptLibrarySource).toContain('图片')
    expect(promptLibrarySource).toContain('视频')
    expect(promptLibrarySource).not.toContain("category === '文本'")
  })
})
