import { describe, expect, it } from 'vitest'
import fs from 'node:fs'
import path from 'node:path'

describe('styles source', () => {
  it('contains only the current desktop shell theme and core layout primitives', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/assets/styles.css'), 'utf8')

    expect(source).toContain("[data-theme='dark']")
    expect(source).not.toContain("[data-theme='light']")
    expect(source).not.toContain("[data-theme='eye-care']")
    expect(source).toContain('.app-shell')
    expect(source).toContain('flex-direction: column;')
    expect(source).toContain('height: 100vh;')
    expect(source).toContain('.shell-grid')
    expect(source).toContain('flex: 1;')
    expect(source).toContain('.shell-grid--simple')
    expect(source).toContain('grid-template-columns: minmax(180px, 10vw) minmax(0, 1fr);')
    expect(source).toContain('.shell-grid__sidebar')
    expect(source).toContain('.shell-grid__workspace')
    expect(source).toContain('.shell-grid__tasks')
    expect(source).toContain('.app-notice-layer')
    expect(source).toContain('.app-notice')
    expect(source).toContain('.app-notice--success')
    expect(source).toContain('.app-notice--error')
    expect(source).toContain('overflow: hidden;')
    expect(source).toContain('.module-scroll')
    expect(source).toContain('.scrollbar-hidden')
    expect(source).toContain('.scrollbar-hidden::-webkit-scrollbar')
    expect(source).toContain('.panel-shell')
    expect(source).toContain('.section-header')
    expect(source).toContain('.panel-content')
    expect(source).toContain('.panel-content--scrollable')
    expect(source).toContain('.panel-content--prompt-library')
    expect(source).toContain('.panel-footer')
    expect(source).toContain('.topbar-contact-actions')
    expect(source).toContain('.topbar-right-actions')
    expect(source).toContain('.topbar-contact-button')
    expect(source).toContain('.topbar-clean-button')
    expect(source).toContain('.topbar-recharge-button')
    expect(source).toContain('.contact-preview-modal')
    expect(source).toContain('.contact-preview-modal__image-grid')
    expect(source).toContain('overflow-y: auto;')
    expect(source).toContain('.app-notice-layer')
    expect(source).toContain('z-index: 60;')
    expect(source).not.toContain('.admin-password-modal')
    expect(source).not.toContain('.admin-api-key-modal')
    expect(source).not.toContain('.topbar-utility-cluster')
    expect(source).not.toContain('.sidebar-shell__current-focus')
    expect(source).not.toContain('.sidebar-menu-button__state')
    expect(source).not.toContain('.task-card__summary')
    expect(source).not.toContain('.task-card__head')
    expect(source).not.toContain('.task-card__footer')
    expect(source).not.toContain('.task-card__error')
    expect(source).not.toContain('.task-card__empty')
    expect(source).not.toContain('.number-stepper')
    expect(source).not.toContain('.stepper-button')
    expect(source).not.toContain('.stepper-value')
    expect(source).not.toContain('.icon-action-button')
    expect(source).not.toContain('.upload-directory-row')
    expect(source).not.toContain('.upload-directory-save')
  })

  it('contains the current workbench, studio, account usage, and prompt library styles', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/assets/styles.css'), 'utf8')

    expect(source).toContain('.product-workbench')
    expect(source).toContain('.product-workbench--agent')
    expect(source).toContain('.workbench-column')
    expect(source).toContain('.workbench-column--results')
    expect(source).toContain('.project-draft-grid--warehouse')
    expect(source).toContain('.project-draft-card')
    expect(source).toContain('.project-task-card__switches')
    expect(source).toContain('.project-task-card__config-grid')
    expect(source).toContain('.product-result-grid--warehouse')
    expect(source).toContain('.product-result-card__detail-row')
    expect(source).toContain('.product-result-card__copy')
    expect(source).toContain('.generator-studio-page')
    expect(source).toContain('.generator-column')
    expect(source).toContain('.generator-progress-layout')
    expect(source).toContain('.generator-progress-pane')
    expect(source).toContain('.latest-task-progress')
    expect(source).toContain('.task-queue-list')
    expect(source).toContain('.task-queue-item')
    expect(source).toContain('.generator-preview-stage')
    expect(source).toContain('.generator-preview__series-grid')
    expect(source).toContain('.generator-preview__video')
    expect(source).toContain('.generator-export')
    expect(source).toContain('.generator-export__item')
    expect(source).toContain('.task-status--waiting')
    expect(source).toContain('.task-status--running')
    expect(source).toContain('.task-status--completed')
    expect(source).toContain('.task-status--failed')
    expect(source).toContain('.task-progress__bar')
    expect(source).toContain('.data-center-page')
    expect(source).toContain('.data-center-panel')
    expect(source).toContain('.credit-gauge-card')
    expect(source).toContain('.credit-record-panel')
    expect(source).toContain('.credit-record-group')
    expect(source).toContain('.prompt-library-grid')
    expect(source).toContain('.prompt-library-column')
    expect(source).toContain('.prompt-template-card')
    expect(source).toContain('.sidebar-shell__brand-orb')
    expect(source).toContain('.secondary-action--compact')
    expect(source).toContain('.project-draft-card__issue-link')
    expect(source).toContain('min-height: 34px;')
    expect(source).toContain('padding: 0 10px;')
    expect(source).toContain('.prompt-library-list')
    expect(source).toContain('.prompt-template-card__content')
    expect(source).toContain('.select-icon-field')
    expect(source).toContain('.select-icon-field select')
    expect(source).toContain('color-scheme: dark;')
    expect(source).toContain('.select-icon-field select option')
    expect(source).toContain('background: var(--panel-strong);')
    expect(source).toContain('@media (max-width: 1680px)')
    expect(source).toContain('@media (max-width: 1440px)')
    expect(source).toContain('@media (max-width: 1360px)')
    expect(source).toContain('@media (max-width: 960px)')
    expect(source).not.toContain('.workspace-panels')
    expect(source).not.toContain('.workspace-dashboard')
    expect(source).not.toContain('.dashboard-network-monitor')
    expect(source).not.toContain('.task-list--paged')
    expect(source).not.toContain('.task-pagination')
    expect(source).not.toContain('.pagination-arrow-button')
    expect(source).not.toContain('.prompt-import-modal')
    expect(source).not.toContain('.comparison-grid')
    expect(source).not.toContain('.preview-modal')
    expect(source).not.toContain('.export-item__actions')
    expect(source).not.toContain('.prompt-library-stack')
    expect(source).not.toContain('.prompt-library-column--sidebar')
    expect(source).not.toContain('.prompt-library-column--negative')
    expect(source).not.toContain('.prompt-library-column--positive')
    expect(source).not.toContain('.prompt-library-column--format')
    expect(source).not.toContain('.prompt-library-subpanel')
    expect(source).not.toContain('.prompt-library-risk-sidebar')
    expect(source).not.toContain('.prompt-library-risk-panel')
    expect(source).not.toContain('.prompt-template-row')
    expect(source).not.toContain('.prompt-template-disclosure')
    expect(source).not.toContain('.prompt-storage-card')
    expect(source).not.toContain('.prompt-template-editor')
    expect(source).not.toContain('.prompt-template-add-button')
  })
})
