const { contextBridge, ipcRenderer } = require('electron')
const ipcChannels = require('../shared/ipcChannels')

const channels = {
  LICENSE_GET_STATUS: ipcChannels.LICENSE_GET_STATUS,
  LICENSE_GET_DEVICE_CODE: ipcChannels.LICENSE_GET_DEVICE_CODE,
  LICENSE_REMOTE_ACTIVATE: ipcChannels.LICENSE_REMOTE_ACTIVATE,
  LICENSE_LIST_PACKAGES: ipcChannels.LICENSE_LIST_PACKAGES,
  LICENSE_CREATE_ORDER: ipcChannels.LICENSE_CREATE_ORDER,
  LICENSE_GET_ORDER: ipcChannels.LICENSE_GET_ORDER,
  LICENSE_GET_USER_AGREEMENT_STATUS: ipcChannels.LICENSE_GET_USER_AGREEMENT_STATUS,
  LICENSE_ACCEPT_USER_AGREEMENT: ipcChannels.LICENSE_ACCEPT_USER_AGREEMENT,
  COMPUTE_PACKAGE_LIST: ipcChannels.COMPUTE_PACKAGE_LIST,
  COMPUTE_PACKAGE_CREATE_ORDER: ipcChannels.COMPUTE_PACKAGE_CREATE_ORDER,
  COMPUTE_PACKAGE_GET_ORDER: ipcChannels.COMPUTE_PACKAGE_GET_ORDER,
  SELECTION_GET_MANIFEST: ipcChannels.SELECTION_GET_MANIFEST,
  SELECTION_LIST_PLATFORMS: ipcChannels.SELECTION_LIST_PLATFORMS,
  SELECTION_LIST_SITES: ipcChannels.SELECTION_LIST_SITES,
  SELECTION_LIST_ITEMS: ipcChannels.SELECTION_LIST_ITEMS,
  SELECTION_GET_ITEM_DETAIL: ipcChannels.SELECTION_GET_ITEM_DETAIL,
  PUBLISH_LIST_CHANNEL_ACCOUNTS: ipcChannels.PUBLISH_LIST_CHANNEL_ACCOUNTS,
  PUBLISH_UPSERT_DRAFT: ipcChannels.PUBLISH_UPSERT_DRAFT,
  PUBLISH_GET_DRAFT: ipcChannels.PUBLISH_GET_DRAFT,
  PUBLISH_GET_DRAFT_PREVIEW: ipcChannels.PUBLISH_GET_DRAFT_PREVIEW,
  PUBLISH_CREATE_TASK: ipcChannels.PUBLISH_CREATE_TASK,
  PUBLISH_GET_TASK: ipcChannels.PUBLISH_GET_TASK,
  PUBLISH_RETRY_TASK: ipcChannels.PUBLISH_RETRY_TASK,
  RECHARGE_CREATE_ORDER: ipcChannels.RECHARGE_CREATE_ORDER,
  RECHARGE_GET_ORDER: ipcChannels.RECHARGE_GET_ORDER,
  PROMPTS_LIST: ipcChannels.PROMPTS_LIST,
  PROMPTS_SAVE: ipcChannels.PROMPTS_SAVE,
  PROMPTS_REMOVE: ipcChannels.PROMPTS_REMOVE,
  STUDIO_GET_SNAPSHOT: ipcChannels.STUDIO_GET_SNAPSHOT,
  STUDIO_GET_RUNTIME_SNAPSHOT: ipcChannels.STUDIO_GET_RUNTIME_SNAPSHOT,
  STUDIO_CREATE_PROJECT: ipcChannels.STUDIO_CREATE_PROJECT,
  STUDIO_UPDATE_PROJECT: ipcChannels.STUDIO_UPDATE_PROJECT,
  STUDIO_DELETE_PROJECT: ipcChannels.STUDIO_DELETE_PROJECT,
  STUDIO_EXPORT_PROJECT_BUNDLE: ipcChannels.STUDIO_EXPORT_PROJECT_BUNDLE,
  STUDIO_SAVE_DRAFT: ipcChannels.STUDIO_SAVE_DRAFT,
  STUDIO_CREATE_TASK: ipcChannels.STUDIO_CREATE_TASK,
  STUDIO_PICK_INPUT_ASSETS: ipcChannels.STUDIO_PICK_INPUT_ASSETS,
  STUDIO_OPEN_OUTPUT_DIRECTORY: ipcChannels.STUDIO_OPEN_OUTPUT_DIRECTORY,
  STUDIO_OPEN_EXTERNAL_RESOURCE: ipcChannels.STUDIO_OPEN_EXTERNAL_RESOURCE,
  STUDIO_EXPORT_RESULTS: ipcChannels.STUDIO_EXPORT_RESULTS,
  STUDIO_CLEAR_RUNTIME_STATE: ipcChannels.STUDIO_CLEAR_RUNTIME_STATE
}

contextBridge.exposeInMainWorld('qiuai', {
  channels,
  invoke (channel, payload) {
    return ipcRenderer.invoke(channel, payload)
  }
})
