import { describe, expect, it } from 'vitest'
import fs from 'node:fs'
import path from 'node:path'

describe('preload source', () => {
  it('exposes qiuai bridge with invoke helper', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'main/preload.js'), 'utf8')
    expect(source).toContain("contextBridge.exposeInMainWorld('qiuai'")
    expect(source).toContain('ipcRenderer.invoke(channel, payload)')
    expect(source).toContain('PROMPTS_LIST')
    expect(source).toContain('LICENSE_GET_STATUS')
    expect(source).toContain('LICENSE_GET_DEVICE_CODE')
    expect(source).toContain('SELECTION_GET_MANIFEST')
    expect(source).toContain('SELECTION_LIST_ITEMS')
    expect(source).toContain('STUDIO_GET_SNAPSHOT')
    expect(source).toContain('STUDIO_SAVE_DRAFT')
    expect(source).toContain('STUDIO_CREATE_TASK')
    expect(source).toContain('STUDIO_PICK_INPUT_ASSETS')
    expect(source).toContain('STUDIO_OPEN_OUTPUT_DIRECTORY')
    expect(source).toContain('STUDIO_EXPORT_RESULTS')
    expect(source).toContain('STUDIO_CLEAR_RUNTIME_STATE')
    expect(source).not.toContain('DRAW_CREATE_TASK')
    expect(source).not.toContain('DRAW_GET_RESULT')
    expect(source).not.toContain('DRAW_DOWNLOAD_IMAGE')
    expect(source).not.toContain('INPUT_PICK_FOLDER')
    expect(source).not.toContain('INPUT_PICK_FILE')
    expect(source).not.toContain('TASKS_CREATE_LOCAL')
    expect(source).not.toContain('TASKS_LIST')
    expect(source).not.toContain('TASKS_GET')
    expect(source).not.toContain('TASKS_RUN')
    expect(source).not.toContain('TASKS_EXPORT')
    expect(source).not.toContain('SETTINGS_SAVE_PROVIDER_API_KEYS')
    expect(source).not.toContain('LICENSE_IMPORT_FILE')
    expect(source).not.toContain('LICENSE_REFRESH')
    expect(source).not.toContain('STUDIO_CREATE_PROJECTS_FROM_ASSETS')
    expect(source).not.toContain('STUDIO_REFRESH_DASHBOARD_CREDITS')
    expect(source).toContain('STUDIO_DELETE_EXPORT_ITEM')
    expect(source).not.toContain('STUDIO_STOP_TASK')
  })
})
